#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal

# Source generated colors.
source "${HOME}/.cache/wal/colors.sh"

reload_dunst() {
    pkill dunst && \
        dunst \
            -lb "$color0" \
            -nb "$color0" \
            -cb "$color0" \
            -lf "$color9"  \
            -bf "$color9"  \
            -cf "$color7" &
}


set_scss() {
    sassc --style expanded "${HOME}/projects/startpage/scss/style.scss" > "${HOME}/projects/startpage/style.css"
}

set_gtk() {


echo 'style "default"
{
  xthickness = 2
  ythickness = 2

  EelEditableLabel::cursor_aspect_ratio = 0.1
  EelEditableLabel::cursor_color    = "'$color13'"

  GtkEntry::cursor_color    = "'$color13'"
  GtkEntry::cursor_aspect_ratio = 0.1

  GtkHSV::focus-line-pattern = "\0"

  GtkRange::stepper-size = 20

  GtkTextView::cursor_aspect_ratio = 0.1
  GtkTextView::cursor_color    = "'$color13'"

  GtkTreeView::expander-size = 16

  GtkWidget::focus-line-pattern = "\4\2"
  GtkWidget::focus-line-width = 2
  GtkWidget::focus-padding = 0
  GtkWidget::interior_focus = 1
  GtkWidget::link-color = "'$color13'"
  GtkWidget::visited-link-color = "'$color14'"

fg[NORMAL] = "'$foreground'"
fg[PRELIGHT] = "'$foreground'"
fg[SELECTED] = "'$foreground'"
fg[ACTIVE] = "'$foreground'"
fg[INSENSITIVE] = mix(0.5, "'$background'", "'$foreground'")

bg[NORMAL] = "'$background'"
bg[PRELIGHT] = shade(2.0, "'$background'")
bg[SELECTED] = "'$background'"
bg[ACTIVE] = shade(1.5, "'$background'")
bg[INSENSITIVE] = "'$background'"

base[NORMAL] = "'$background'"
base[PRELIGHT] = "'$background'"
base[SELECTED] = "'$color1'"
base[ACTIVE] = "'$color1'"
base[INSENSITIVE] = shade(0.85, "'$background'")

text[NORMAL] = "'$foreground'"
text[PRELIGHT] = "'$foreground'"
text[SELECTED] = "'$foreground'"
text[ACTIVE] = "'$foreground'"
text[INSENSITIVE] = shade(0.85, "'$foreground'")

}

class "GtkWidget" style "default"

# widget "*PanelWidget*" style "panel"
# widget "*PanelApplet*" style "panel"
# class "*Panel*" style "panel"
# widget_class "*Applet*" style "panel"
# class "*notif*" style "panel"
# class "*Notif*" style "panel"
# class "*Tray*" style "panel"
# class "*tray*" style "panel"
' > ${HOME}/.gtkrc-2.0.mine

}

home() {
    yes | cp -rf $wallpaper ${HOME}/Code/home/app/images/wallpaper.jpg
}

vscode() {
    yes | cp -rf ${HOME}/.cache/wal/colors.vscode.json ${HOME}/.vscode/extensions/pywal-theme/themes/pywal-theme-color-theme.json
}

main() {
    set_gtk &
    reload_dunst &
    home &
    vscode &
}

main >/dev/null 2>&1
