# Shell variables
# Generated by 'wal'
wallpaper='/mnt/share/backgrounds/1361000718153.jpg'

# Special
background='#080808'
foreground='#99E5FD'
cursor='#99E5FD'

# Colors
color0='#080808'
color1='#464545'
color2='#535353'
color3='#65696A'
color4='#0B7091'
color5='#268EB0'
color6='#56BDDF'
color7='#99E5FD'
color8='#6a6a6a'
color9='#464545'
color10='#535353'
color11='#65696A'
color12='#0B7091'
color13='#268EB0'
color14='#56BDDF'
color15='#99E5FD'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
